(define-module (conner packages virtiofsd)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix gexp)
  #:use-module (guix utils)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system cargo)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages tcl)
  #:use-module (gnu packages networking)
  #:use-module (conner packages rust-crates)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages base)
  #:use-module (gnu packages multiprecision)
  #:use-module (gnu packages admin))

(define-public virtiofsd
  (package
    (name "virtiofsd")
    (version "1.13.2")
    (source
     (origin
       (method url-fetch)
       (uri (crate-uri "virtiofsd" version))
       (file-name (string-append name "-" version ".tar.gz"))
       (sha256
        (base32 "0jni7dxc6biqi44gh8bzjx98y78f5i28my85y9g15pm1qvy596rs"))))
    (build-system cargo-build-system)
    (inputs (cons* libseccomp libcap-ng (cargo-inputs 'virtiofsd #:module '(conner packages rust-crates))))
    (home-page "https://virtio-fs.gitlab.io/")
    (synopsis "virtio-fs vhost-user device daemon")
    (description "This package provides a virtio-fs vhost-user device daemon.")
    (license (list license:asl2.0 license:bsd-3))))
